/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.userlogin.igu;

import com.mycompany.userlogin.logica.control;
import com.mycompany.userlogin.logica.Usuario;
import java.awt.Color;
import java.awt.Dialog;
import java.util.List;
import javax.swing.JOptionPane;

public class loginuser extends javax.swing.JFrame {

    control cont = null;
    int xMouse, yMouse;

    public loginuser() {
        cont = new control();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        imgbase = new javax.swing.JLabel();
        imguser = new javax.swing.JLabel();
        imglogo = new javax.swing.JLabel();
        Contraseña = new javax.swing.JLabel();
        InciarSesion = new javax.swing.JLabel();
        Usuario1 = new javax.swing.JLabel();
        inputUsu = new javax.swing.JTextField();
        inputContr = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        btnEnter = new javax.swing.JPanel();
        txtEnter = new javax.swing.JLabel();
        panelBarra = new javax.swing.JPanel();
        btnExit = new javax.swing.JPanel();
        txtExit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgbase.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imgbase.setIcon(new javax.swing.ImageIcon("D:\\CARPETAS D\\Steeven Rodriguez\\Programacion\\Java Tocode\\UserLogin\\src\\main\\java\\imagenes\\informacion.png")); // NOI18N
        jPanel1.add(imgbase, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 270, 210));

        imguser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imguser.setIcon(new javax.swing.ImageIcon("D:\\CARPETAS D\\Steeven Rodriguez\\Programacion\\Java Tocode\\UserLogin\\src\\main\\java\\imagenes\\acceso.png")); // NOI18N
        jPanel1.add(imguser, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 310, 270, 190));

        imglogo.setIcon(new javax.swing.ImageIcon("D:\\CARPETAS D\\Steeven Rodriguez\\Programacion\\Java Tocode\\UserLogin\\src\\main\\java\\imagenes\\city.png")); // NOI18N
        jPanel1.add(imglogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, 270, 510));

        Contraseña.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        Contraseña.setForeground(new java.awt.Color(0, 0, 0));
        Contraseña.setText("CONTRASEÑA:");
        jPanel1.add(Contraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));

        InciarSesion.setFont(new java.awt.Font("Roboto Black", 1, 36)); // NOI18N
        InciarSesion.setForeground(new java.awt.Color(0, 0, 0));
        InciarSesion.setIcon(new javax.swing.ImageIcon("D:\\CARPETAS D\\Steeven Rodriguez\\Programacion\\Java Tocode\\UserLogin\\src\\main\\java\\imagenes\\Userlogin.png")); // NOI18N
        InciarSesion.setText("INICIAR SESIÓN");
        jPanel1.add(InciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        Usuario1.setFont(new java.awt.Font("Roboto Black", 1, 24)); // NOI18N
        Usuario1.setForeground(new java.awt.Color(0, 0, 0));
        Usuario1.setText("USUARIO:");
        jPanel1.add(Usuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        inputUsu.setBackground(new java.awt.Color(255, 255, 255));
        inputUsu.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        inputUsu.setForeground(new java.awt.Color(204, 204, 204));
        inputUsu.setText("Ingrese el Usuario");
        inputUsu.setBorder(null);
        inputUsu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                inputUsuMousePressed(evt);
            }
        });
        inputUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputUsuActionPerformed(evt);
            }
        });
        jPanel1.add(inputUsu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 280, 30));

        inputContr.setBackground(new java.awt.Color(255, 255, 255));
        inputContr.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        inputContr.setText("********************");
        inputContr.setToolTipText("");
        inputContr.setBorder(null);
        inputContr.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                inputContrMousePressed(evt);
            }
        });
        jPanel1.add(inputContr, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 280, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 300, -1));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 300, 10));

        btnEnter.setBackground(new java.awt.Color(0, 134, 190));
        btnEnter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEnter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEnterMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEnterMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEnterMouseExited(evt);
            }
        });

        txtEnter.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        txtEnter.setForeground(new java.awt.Color(255, 255, 255));
        txtEnter.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtEnter.setIcon(new javax.swing.ImageIcon("D:\\CARPETAS D\\Steeven Rodriguez\\Programacion\\Java Tocode\\UserLogin\\src\\main\\java\\imagenes\\ingresarUser.png")); // NOI18N
        txtEnter.setText("INGRESAR");

        javax.swing.GroupLayout btnEnterLayout = new javax.swing.GroupLayout(btnEnter);
        btnEnter.setLayout(btnEnterLayout);
        btnEnterLayout.setHorizontalGroup(
            btnEnterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtEnter, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
        );
        btnEnterLayout.setVerticalGroup(
            btnEnterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtEnter, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(btnEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 420, 170, 40));

        panelBarra.setBackground(new java.awt.Color(255, 255, 255));
        panelBarra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                panelBarraMouseDragged(evt);
            }
        });
        panelBarra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                panelBarraMousePressed(evt);
            }
        });

        btnExit.setBackground(new java.awt.Color(255, 255, 255));

        txtExit.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txtExit.setForeground(new java.awt.Color(0, 0, 0));
        txtExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtExit.setText("X");
        txtExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        txtExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtExitMouseExited(evt);
            }
        });

        javax.swing.GroupLayout btnExitLayout = new javax.swing.GroupLayout(btnExit);
        btnExit.setLayout(btnExitLayout);
        btnExitLayout.setHorizontalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtExit, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
        );
        btnExitLayout.setVerticalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnExitLayout.createSequentialGroup()
                .addComponent(txtExit, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelBarraLayout = new javax.swing.GroupLayout(panelBarra);
        panelBarra.setLayout(panelBarraLayout);
        panelBarraLayout.setHorizontalGroup(
            panelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarraLayout.createSequentialGroup()
                .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 847, Short.MAX_VALUE))
        );
        panelBarraLayout.setVerticalGroup(
            panelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarraLayout.createSequentialGroup()
                .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(panelBarra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 50));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelBarraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBarraMousePressed
        xMouse = evt.getX();
       yMouse = evt.getY();
    }//GEN-LAST:event_panelBarraMousePressed

    private void panelBarraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelBarraMouseDragged
       int x = evt.getXOnScreen();
       int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_panelBarraMouseDragged

    private void txtExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_txtExitMouseClicked

    private void txtExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseEntered
        btnExit.setBackground(Color.red);
        txtExit.setForeground(Color.white);
    }//GEN-LAST:event_txtExitMouseEntered

    private void txtExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtExitMouseExited
        btnExit.setBackground(Color.white);
        txtExit.setForeground(Color.black);
    }//GEN-LAST:event_txtExitMouseExited

    private void inputUsuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputUsuMousePressed
        inputUsu.setText("");
        inputUsu.setForeground(Color.black);
    }//GEN-LAST:event_inputUsuMousePressed

    private void inputUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputUsuActionPerformed

    private void inputContrMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputContrMousePressed
        inputContr.setText("");
        inputContr.setForeground(Color.black);
    }//GEN-LAST:event_inputContrMousePressed

    private void btnEnterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnterMouseClicked
        String usuario = inputUsu.getText();
        String contrasenia = inputContr.getText();
        
        String mensajeok = cont.validarLogin(usuario,contrasenia);
        JOptionPane.showMessageDialog(null, mensajeok);
        if(mensajeok.equals("Bienvenido Administrador")){
            this.dispose();
        }
        
    }//GEN-LAST:event_btnEnterMouseClicked

    private void btnEnterMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnterMouseEntered
        btnEnter.setBackground(new Color(0, 156, 223));
    }//GEN-LAST:event_btnEnterMouseEntered

    private void btnEnterMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnterMouseExited
        btnEnter.setBackground(new Color(0, 134, 190));
    }//GEN-LAST:event_btnEnterMouseExited

    public void mostrarMensaje(String mensaje, String tipo, String titulo) {
        JOptionPane panel = new JOptionPane(mensaje);
        if (tipo.equals("Info")) {
            panel.setMessageType(JOptionPane.INFORMATION_MESSAGE);
        } else if (tipo.equals("Error")) {
            panel.setMessageType(JOptionPane.ERROR_MESSAGE);
        }
        Dialog dialogo = panel.createDialog(titulo);
        dialogo.setVisible(true);
        dialogo.setLocationRelativeTo(null);
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Contraseña;
    private javax.swing.JLabel InciarSesion;
    private javax.swing.JLabel Usuario1;
    private javax.swing.JPanel btnEnter;
    private javax.swing.JPanel btnExit;
    private javax.swing.JLabel imgbase;
    private javax.swing.JLabel imglogo;
    private javax.swing.JLabel imguser;
    private javax.swing.JPasswordField inputContr;
    private javax.swing.JTextField inputUsu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel panelBarra;
    private javax.swing.JLabel txtEnter;
    private javax.swing.JLabel txtExit;
    // End of variables declaration//GEN-END:variables
}
